/** Pranit Jaiswal
 * (ID: pxj6023) */
package client;

import com.opencsv.CSVReader;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.User;
import server.ServerScreen;
import utils.CSVReaderInJava;
import utils.Constants;
import utils.Utils;

//  Class to implement Client along with Client GUI
//  Reference URL : http://www.srikanthtechnologies.com/blog/java/chatdemo.aspx
public class ClientScreen extends javax.swing.JFrame {

    String uname;
    PrintWriter pw;
    BufferedReader br;
    Socket client;

    String MESSAGE_TYPE = "Unicast";
    String UNICAST_USERNAME = "";
    String MULTICAST_USERLIST = "";

    HashMap<String, Integer> vector_clock = new HashMap<String, Integer>();
    String vector_clock_str = "0,0,0";

    Timer sendMessageTimer;

    public ClientScreen() {

    }

    /**
     * Creates new form ClientScreen
     */
    public ClientScreen(String uname) throws Exception {
        super(uname);           // set title for frame
        this.uname = uname;     // initialize client username

        validateAndStartClientThread(uname); // call method to validate client and start client thread       
    }

    // Method to validate client and start client threrad
    private void validateAndStartClientThread(String uname) {

        //check if user is already online
        boolean isUserOnline = checkUserOnline();

        if (isUserOnline) {             // if user is already online then show an error and terminate the current window
            JOptionPane.showMessageDialog(null, uname + " is already logged-in", "Error", JOptionPane.ERROR_MESSAGE);
            terminateWindow();
        } else {                        // if user is not online then create new client

            try {
                // create new socket for client using pre-defined servername and port number
                client = new Socket(Constants.SERVER_NAME, Constants.PORT_NUMBER);

                // check if user already exists in userLog present in CSV file
                boolean isUserExist = checkUserStatus();
                if (!isUserExist) {
                    appendNewUserToCSV();   // call method to append new user in CSV file
                }

                // get input and output streams 
                br = new BufferedReader(new InputStreamReader(client.getInputStream()));
                pw = new PrintWriter(client.getOutputStream(), true);

                // send client name to server
                pw.println(uname);

                // customize parameters of frame
                customizeFrame();

                // initialize all UI components of frame
                initComponents();

                // make the frame visible
                setVisible(true);

                // hide unwanted UI from the frame
                hideUnwantedUI();

                // create and start new thread to read incoming messages from server
                new MessagesThread().start();

                // refresh the userLog to display on screen
                refreshListOfUsers();

                initializeVectorClock();
                //startSendingMessage();

            } catch (Exception e) {
                // show error dialog if server is not running and terminate the current window
                JOptionPane.showMessageDialog(null, "Server not running", "Error", JOptionPane.ERROR_MESSAGE);
                terminateWindow();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        userListScrollPane = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        username_ta = new javax.swing.JTextArea();
        status_ta = new javax.swing.JTextArea();
        timestamp_ta = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        unicast_rb = new javax.swing.JRadioButton();
        multicast_rb = new javax.swing.JRadioButton();
        broadcast_rb = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enter_username_panel = new javax.swing.JPanel();
        enter_username_label = new javax.swing.JLabel();
        enter_username_textfield = new javax.swing.JTextField();
        multicast_note_scrollpane = new javax.swing.JScrollPane();
        multicast_note_ta = new javax.swing.JTextArea();
        input_message_panel = new javax.swing.JPanel();
        message_label = new javax.swing.JLabel();
        message_tf = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        textAreaScrollPane = new javax.swing.JScrollPane();
        chat_area_ta = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        userListScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        username_ta.setEditable(false);
        username_ta.setColumns(20);
        username_ta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        username_ta.setRows(50);
        username_ta.setFocusable(false);
        username_ta.setMargin(new java.awt.Insets(5, 10, 5, 10));

        status_ta.setEditable(false);
        status_ta.setColumns(20);
        status_ta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        status_ta.setRows(5);
        status_ta.setFocusable(false);
        status_ta.setMargin(new java.awt.Insets(5, 10, 5, 10));

        timestamp_ta.setEditable(false);
        timestamp_ta.setColumns(20);
        timestamp_ta.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        timestamp_ta.setRows(5);
        timestamp_ta.setFocusable(false);
        timestamp_ta.setMargin(new java.awt.Insets(5, 10, 5, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status_ta, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timestamp_ta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_ta, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(status_ta)
                    .addComponent(timestamp_ta))
                .addContainerGap())
        );

        userListScrollPane.setViewportView(jPanel6);

        buttonGroup1.add(unicast_rb);
        unicast_rb.setText("Unicast");
        unicast_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unicast_rbActionPerformed(evt);
            }
        });

        buttonGroup1.add(multicast_rb);
        multicast_rb.setSelected(true);
        multicast_rb.setText("Multicast");
        multicast_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multicast_rbActionPerformed(evt);
            }
        });

        buttonGroup1.add(broadcast_rb);
        broadcast_rb.setText("Broadcast");
        broadcast_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broadcast_rbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Choose type :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unicast_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multicast_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(broadcast_rb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unicast_rb)
                    .addComponent(multicast_rb)
                    .addComponent(broadcast_rb)
                    .addComponent(jLabel6)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Online Status");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Recent Log-in");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        enter_username_label.setText("Enter Username:");

        //multicast_note_scrollpane.setVisible(false);

        multicast_note_ta.setEditable(false);
        multicast_note_ta.setBackground(new java.awt.Color(204, 204, 204));
        multicast_note_ta.setColumns(20);
        multicast_note_ta.setFont(new java.awt.Font("Monospaced", 2, 13)); // NOI18N
        multicast_note_ta.setRows(5);
        multicast_note_ta.setText("Note: For Multicast - \nEnter usernames separated with comma (,)\n\neg. John, Emma, Maria, David");
        multicast_note_ta.setAutoscrolls(false);
        multicast_note_scrollpane.setViewportView(multicast_note_ta);

        javax.swing.GroupLayout enter_username_panelLayout = new javax.swing.GroupLayout(enter_username_panel);
        enter_username_panel.setLayout(enter_username_panelLayout);
        enter_username_panelLayout.setHorizontalGroup(
            enter_username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_username_panelLayout.createSequentialGroup()
                .addComponent(enter_username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_username_textfield))
            .addComponent(multicast_note_scrollpane)
        );
        enter_username_panelLayout.setVerticalGroup(
            enter_username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_username_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enter_username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_username_label)
                    .addComponent(enter_username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(multicast_note_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        message_label.setText("Message:");

        javax.swing.GroupLayout input_message_panelLayout = new javax.swing.GroupLayout(input_message_panel);
        input_message_panel.setLayout(input_message_panelLayout);
        input_message_panelLayout.setHorizontalGroup(
            input_message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_message_panelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(message_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        input_message_panelLayout.setVerticalGroup(
            input_message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_message_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(input_message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message_label)
                    .addComponent(message_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        send_btn.setBackground(new java.awt.Color(0, 153, 153));
        send_btn.setForeground(new java.awt.Color(255, 255, 255));
        send_btn.setText("Start Sending Messages");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(input_message_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userListScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enter_username_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_btn)
                .addGap(168, 168, 168))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_username_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(input_message_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chat_area_ta.setEditable(false);
        chat_area_ta.setColumns(20);
        chat_area_ta.setRows(5);
        textAreaScrollPane.setViewportView(chat_area_ta);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Message Log :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        logout_btn.setBackground(new java.awt.Color(153, 0, 0));
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to call when user clicks on "send button"
    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
        //methodToCallAfterSendClick();
        startSendingMessage();
    }//GEN-LAST:event_send_btnActionPerformed

    // Method to call when user clicks on "unicast radiobutton"
    private void unicast_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unicast_rbActionPerformed
        // TODO add your handling code here:
        enter_username_panel.setVisible(true);
        multicast_note_scrollpane.setVisible(false);
        MESSAGE_TYPE = "Unicast";
        //System.out.println("Pranit : RadioButtonTest : ClientScreen : clicked on unicast_rb");
    }//GEN-LAST:event_unicast_rbActionPerformed

    // Method to call when user clicks on "multicast radiobutton"
    private void multicast_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multicast_rbActionPerformed
        // TODO add your handling code here:
        enter_username_panel.setVisible(true);
        multicast_note_scrollpane.setVisible(true);
        MESSAGE_TYPE = "Multicast";
        //System.out.println("Pranit : RadioButtonTest : ClientScreen : clicked on multicast_rb");

    }//GEN-LAST:event_multicast_rbActionPerformed

    // Method to call when user clicks on "broadcast radiobutton"
    private void broadcast_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broadcast_rbActionPerformed
        // TODO add your handling code here:
        enter_username_panel.setVisible(false);
        multicast_note_scrollpane.setVisible(false);
        MESSAGE_TYPE = "Broadcast";
        //System.out.println("Pranit : RadioButtonTest : ClientScreen : clicked on broadcast_rb");

    }//GEN-LAST:event_broadcast_rbActionPerformed

    // Method to call when user clicks on "logout button"
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        finishMyClient();
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ClientScreen mClientScreen = new ClientScreen();

        // Create InputDialog take username from user
        String name = JOptionPane.showInputDialog(null, "Enter your name :", "Username (Only A-Z and a-z)", JOptionPane.PLAIN_MESSAGE);
        name = name.trim();
        name = name.toUpperCase();

        if (name == null) {                                     // if user clicks on "cancel" button of InputDialog                   
            mClientScreen.terminateWindow();                    // terminate the window
        } else {
            if (name.isEmpty() || name.equals("")) {            // if username provided is Empty
                JOptionPane.showMessageDialog(null, "Username should not be empty", "Invalid Username", JOptionPane.ERROR_MESSAGE); // show dialog as "Invalid Username"
                mClientScreen.terminateWindow();                // terminate the window
            } else {
                if (Utils.isAlpha(name)) {                      // check whether the username provided is alphnumeric or not

                    if (name.equalsIgnoreCase("A") || name.equalsIgnoreCase("B") || name.equalsIgnoreCase("C")) {
                        try {
                            mClientScreen = new ClientScreen(name); // Create and display the form
                        } catch (Exception ex) {
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Only 3 usernames are allowed ('A' or 'B' or 'C')", "Invalid Username", JOptionPane.ERROR_MESSAGE);
                        mClientScreen.terminateWindow();            // terminate the window
                    }

                } else {
                    // if username contains anything else than alphabates then show dialog as "Invalid Username"
                    JOptionPane.showMessageDialog(null, "Only 3 usernames are allowed ('A' or 'B' or 'C')", "Invalid Username", JOptionPane.ERROR_MESSAGE);
                    mClientScreen.terminateWindow();            // terminate the window
                }
            }
        }
    }

    // Method to hide unwanted UI from frame
    private void hideUnwantedUI() {
        jPanel1.setVisible(false);
        enter_username_panel.setVisible(false);
        input_message_panel.setVisible(false);
    }

    // Method to finish the client if Client wants to disconnect manually
    private void finishMyClient() {
        //Edit online status of user in CSV before terminating the application
        editCSVBeforeClose();

        // send "close_client" message to server so that server knows about the termination
        pw.println(Constants.MESSAGE_TO_CLOSE_CLIENT);

        // stop timer to send message
        stopTimerToSendMessage();

        // show dialog for "Logout successful"
        JOptionPane.showMessageDialog(null, "Logout successful", "" + uname, JOptionPane.INFORMATION_MESSAGE);

        // terminate the window
        terminateWindow();
    }

    // Method to finish the client if Server is closed (if no server is running then all clients must disconnect)
    private void closeClientRequestFromServer() {
        //Edit online status of user in CSV before terminating the application
        editCSVBeforeClose();

        // stop timer to send message
        stopTimerToSendMessage();

        // terminate the window
        terminateWindow();
    }

    // Method to terminate the window
    private void terminateWindow() {
        System.exit(0);     // Terminates instance of the runningg application
    }

    // Method to customize the frame before making it visible
    private void customizeFrame() {
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //finishMyClient();
            }
        });
    }

    // Method to check if the new user alerady exist and for editing log of existing user
    private boolean checkUserStatus() {

        // read latest userLog available in CSV file
        CSVReaderInJava.readUsersFromCSV(Constants.CSV_FILEPATH + "\\" + Constants.CSV_FILENAME);

        boolean isUserExist = false;

        // loop to iterate all usernames present in the CSV file
        for (int i = 0; i < CSVReaderInJava.users.size(); i++) {

            if (CSVReaderInJava.users.get(i).getUsername().equalsIgnoreCase(uname)) {                       // if new username matches with existing username in the csv file then
                isUserExist = true;

                if (!CSVReaderInJava.users.get(i).getStatus().equalsIgnoreCase(Constants.STATUS.ONLINE)) {  // if user is not already online

                    // get new timestamp from system
                    String timestamp = Utils.getDateAndTimeFromTimeStamp(System.currentTimeMillis(), Constants.DATE_FORMAT_FULL_DATE_TIME);

                    // set this timestamp for the user in userModel
                    CSVReaderInJava.users.get(i).setTimestamp(timestamp);

                    // update status to "Online" for the user in userModel
                    CSVReaderInJava.users.get(i).setStatus(Constants.STATUS.ONLINE);

                    // update the CSV with the new user model
                    rewriteCSV();
                }

                break;
            }

        }

        return isUserExist;
    }

    private boolean checkUserOnline() {

        // read latest userLog available in CSV file
        CSVReaderInJava.readUsersFromCSV(Constants.CSV_FILEPATH + "\\" + Constants.CSV_FILENAME);

        boolean isUserOnline = false;

        // loop to iterate all usernames present in the CSV file
        for (int i = 0; i < CSVReaderInJava.users.size(); i++) {

            if (CSVReaderInJava.users.get(i).getUsername().equalsIgnoreCase(uname)) {   // if new username matches with existing username in the csv file then

                if (CSVReaderInJava.users.get(i).getStatus().equalsIgnoreCase(Constants.STATUS.ONLINE)) {   // if user is not already online
                    isUserOnline = true;    // set isUserOnline as true
                } else {
                    isUserOnline = false;   // set isUserOnline as false
                }

                break;
            }

        }

        return isUserOnline;
    }

    // Method to append new User to CSV file
    private void appendNewUserToCSV() {
        // get System timestamp
        String timestamp = Utils.getDateAndTimeFromTimeStamp(System.currentTimeMillis(), Constants.DATE_FORMAT_FULL_DATE_TIME);

        // append data in csv
        Utils.appendDataToNextLineCSV(uname, timestamp, Constants.STATUS.ONLINE);
    }

    // Method to save all user data in CSV before closing the ative client
    private void editCSVBeforeClose() {

        // read latest userLog available in CSV file
        CSVReaderInJava.readUsersFromCSV(Constants.CSV_FILEPATH + "\\" + Constants.CSV_FILENAME);

        // loop to iterate all usernames present in the CSV file
        for (int i = 0; i < CSVReaderInJava.users.size(); i++) {
            if (CSVReaderInJava.users.get(i).getUsername().equalsIgnoreCase(uname)) {    // if new username matches with existing username in the csv file then

                // Store the details of each user in a CSV file
                String timestamp = Utils.getDateAndTimeFromTimeStamp(System.currentTimeMillis(), Constants.DATE_FORMAT_FULL_DATE_TIME);
                CSVReaderInJava.users.get(i).setTimestamp(timestamp);
                CSVReaderInJava.users.get(i).setStatus(Constants.STATUS.OFFLINE);

                rewriteCSV();

                break;
            }
        }

    }

    // Method to rewrite CSV File
    private void rewriteCSV() {
        List<String[]> users = new ArrayList<String[]>();
        for (int j = 0; j < CSVReaderInJava.users.size(); j++) {
            users.add(new String[]{CSVReaderInJava.users.get(j).getUsername(), CSVReaderInJava.users.get(j).getTimestamp(), CSVReaderInJava.users.get(j).getStatus()});
        }
        Utils.writeDataAtOnce(users);
    }

    // inner class for Messages Thread
    class MessagesThread extends Thread {

        public void run() {
            String line;
            try {
                while (true) {
                    // read message input from server
                    line = br.readLine();

                    // perform action based on the message
                    if (line.equals(Constants.MESSAGE_TO_UPDATE_USER_LIST)) {
                        refreshListOfUsers();                   // refresh userLog and display on screen
                    } else if (line.equals(Constants.MESSAGE_TO_CLOSE_ALL_CONNECTED_CLIENTS)) {
                        closeClientRequestFromServer();         // disconnect this client from server and terminate window
                    } else {
                        // show updated vector clock on chat area
                        updateLocalVectorClockForReceiveEvent(line);
                    }

                } // end of while
            } catch (Exception ex) {
            }
        }
    }

    // Method to check conditions for Unicast and send Unicast message
    private void checkConditionsForUnicast(String input_username, String messageToSend) {
        boolean unicast_user_found = false;
        String unicast_user_status = Constants.STATUS.OFFLINE;

        //UNICAST_USERNAME = enter_username_textfield.getText().toString().trim();    // getUsername
        if (!Utils.isAlpha(UNICAST_USERNAME)) {
            // Show error dialog if username contains anything other than alphabets
            JOptionPane.showMessageDialog(null, "Only 3 usernames are allowed ('A' or 'B' or 'C')", "Invalid Username", JOptionPane.ERROR_MESSAGE);
        } else {

            if (UNICAST_USERNAME.equalsIgnoreCase(uname)) {
                // Show error dialog if user try to send message to himself/herself
                JOptionPane.showMessageDialog(null, "You cannot send message to yourself\n\nKindly change it and try again", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                for (int i = 0; i < CSVReaderInJava.users.size(); i++) {
                    // Check if receiver is present
                    if (CSVReaderInJava.users.get(i).getUsername().equalsIgnoreCase(UNICAST_USERNAME)) {
                        unicast_user_found = true;
                        unicast_user_status = CSVReaderInJava.users.get(i).getStatus().trim();
                        break;
                    }
                }

                if (unicast_user_found) {
                    // If user is present then
                    if (unicast_user_status.equals(Constants.STATUS.ONLINE)) {
                        // If user is online then create and message using message format
                        messageToSend = messageToSend + Constants.MESSAGE_SPLITTER_KEYWORD + MESSAGE_TYPE + Constants.MESSAGE_SPLITTER_KEYWORD + UNICAST_USERNAME;
                        pw.println(messageToSend);

                        // print detailed message on message log for showing vector clocks
                        printLocalVectorForSendEvent();
                    } else {
                        // Show dialog if user is offline
                        JOptionPane.showMessageDialog(null, "User \"" + UNICAST_USERNAME + "\" is currently offline. Kindly try again later.", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    // Show dialog if user not found
                    JOptionPane.showMessageDialog(null, "User \"" + UNICAST_USERNAME + "\" not found. Kindly try different username", "User not found", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }

    // Method to refreshListOfUsers
    private void refreshListOfUsers() {

        // Clear all textfields
        username_ta.setText("");
        status_ta.setText("");
        timestamp_ta.setText("");

        // read latest userLog available in CSV file
        CSVReaderInJava.readUsersFromCSV(Constants.CSV_FILEPATH + "\\" + Constants.CSV_FILENAME);

        // loop to iterate all usernames present in the CSV file
        for (int i = 0; i < CSVReaderInJava.users.size(); i++) {
            String username = CSVReaderInJava.users.get(i).getUsername();

            if (!username.equalsIgnoreCase(uname)) {

                username_ta.append(CSVReaderInJava.users.get(i).getUsername() + "\n\n");
                status_ta.append(CSVReaderInJava.users.get(i).getStatus() + "\n\n");
                timestamp_ta.append(CSVReaderInJava.users.get(i).getTimestamp() + "\n\n");
            }

        }

    }

    // Method to initialize Vector Clocks for all clients to 0
    private void initializeVectorClock() {
        vector_clock.put("A", 0);
        vector_clock.put("B", 0);
        vector_clock.put("C", 0);
    }

    // Method to start sending messages
    private void startSendingMessage() {
        // get random delay to send message
        int random_delay = getRandomDelayToSendMessage();
        System.out.println("Pranit : ClientScreen : startSendingMessage : random_delay :" + random_delay);

        // get random index to choose the receiver
        int random_index = generateRandomNumber(0, 1);
        System.out.println("Pranit : ClientScreen : getRandomUserToSendMessage : random_index :" + random_index);

        // get random username as recipient
        UNICAST_USERNAME = getRandomUserToSendMessage(random_index);

        // stop old timer instance running if any
        stopTimerToSendMessage();

        // start new timer instance to send message using random delay
        startTimerToSendMessage(random_delay);
    }

    // Method to get Random Delay to send message
    private int getRandomDelayToSendMessage() {
        return generateRandomNumber(Constants.MIN_DELAY_IN_SEC, Constants.MAX_DELAY_IN_SEC);
    }

    // Method to get Random Username as recipient
    private String getRandomUserToSendMessage(int random_index) {
        String random_user = "";

        // switch-case applied for client name to choose random recipient using random index value
        switch (uname) {
            case "A":
                if (random_index == 0) {
                    random_user = "B";
                } else {
                    random_user = "C";
                }
                break;
            case "B":
                if (random_index == 0) {
                    random_user = "A";
                } else {
                    random_user = "C";
                }
                break;
            case "C":
                if (random_index == 0) {
                    random_user = "A";
                } else {
                    random_user = "B";
                }
                break;
        }

        return random_user;
    }

    // Method to generate random number
    private int generateRandomNumber(int min, int max) {
        int random_num = (int) (Math.random() * (max - min + 1) + min);

        return random_num;
    }

    // Method to stop timer instance
    private void stopTimerToSendMessage() {
        if (sendMessageTimer != null) {
            sendMessageTimer.cancel();
            sendMessageTimer = null;
        }
    }

    // Method to start timer instance
    private void startTimerToSendMessage(int random_delay) {
        // initialize timer variable
        sendMessageTimer = new Timer();

        // schedule timer for the given random delay in seconds
        sendMessageTimer.schedule(new TimerTask() {
            public void run() {
                // update local vector value for send event after random delay in seconds
                updateLocalVectorClockForSendEvent();
            }
        }, random_delay * 1000);
    }

    // Method to update local vector clock for send event
    private void updateLocalVectorClockForSendEvent() {
        // increment local vector clock value for current client
        int vector = vector_clock.get(uname) + 1;

        // put client username and vector clock value as (key,val) pair in hashmap
        vector_clock.put(uname, vector);

        // build vector clock string to send as a message on server
        vector_clock_str = vector_clock.get("A") + "," + vector_clock.get("B") + "," + vector_clock.get("C");
        System.out.println("Pranit : ClientScreen : updateLocalVectorClockForSendEvent : vector_clock_str :" + vector_clock_str);

        // send unicast message to randomly selected recipient
        checkConditionsForUnicast(UNICAST_USERNAME, vector_clock_str);
    }

    // Method to print local vector clock values for send event
    private void printLocalVectorForSendEvent() {
        // get date-time using system timestamp
        String datetime = Utils.getDateAndTimeFromTimeStamp(System.currentTimeMillis(), Constants.DATE_FORMAT_FULL_DATE_TIME);

        // show message on chat area
        chat_area_ta.append(datetime + "  :  " + uname + " to " + UNICAST_USERNAME + "  :  (" + vector_clock_str + ")\n");

        // again start sending random message
        startSendingMessage();
    }

    // Method to update local vector clock for receive event
    private void updateLocalVectorClockForReceiveEvent(String line) {
        // split incoming message line using vector_splitter_keyword
        String[] parts = line.split(Constants.VECTOR_SPLITTER_KEYWORD);

        // assign splitted values to sender_receiver and vector_str variables
        String sender_receiver = parts[0];
        String vector_str = parts[1];

        // further split vector_str using comma (,) to get individual clock value for each client
        String[] vector_parts = vector_str.split(",");

        // store incoming vector value for each client
        int vector_part_A = Integer.parseInt(vector_parts[0]);
        int vector_part_B = Integer.parseInt(vector_parts[1]);
        int vector_part_C = Integer.parseInt(vector_parts[2]);

        // get local vector clock value for current client
        int vectorA = vector_clock.get("A");
        int vectorB = vector_clock.get("B");
        int vectorC = vector_clock.get("C");

        // compare local vector values with the incoming vector values
        // increment vector value which is higher
        if (vector_part_A < vectorA) {
            vector_part_A = vectorA;
        }

        if (vector_part_B < vectorB) {
            vector_part_B = vectorB;
        }

        if (vector_part_C < vectorC) {
            vector_part_C = vectorC;
        }

        // switch-case to increment the vector value for current client
        switch (uname) {
            case "A":
                vector_part_A++;
                break;
            case "B":
                vector_part_B++;
                break;
            case "C":
                vector_part_C++;
                break;
        }

        // update local vector with new values
        vector_clock.put("A", vector_part_A);
        vector_clock.put("B", vector_part_B);
        vector_clock.put("C", vector_part_C);

        // update local vector string to print on message log
        vector_clock_str = vector_clock.get("A") + "," + vector_clock.get("B") + "," + vector_clock.get("C");

        // print detailed message on message log for showing vector clocks
        printLocalVectorForReceiveEvent(sender_receiver);
    }

    // Method to print local vector clock values for receive event
    private void printLocalVectorForReceiveEvent(String sender_receiver) {
        // get date-time using system timestamp
        String datetime = Utils.getDateAndTimeFromTimeStamp(System.currentTimeMillis(), Constants.DATE_FORMAT_FULL_DATE_TIME);

        // show message on chat area
        chat_area_ta.append(datetime + "  :  " + sender_receiver + "  :  (" + vector_clock_str + ")\n");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton broadcast_rb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea chat_area_ta;
    private javax.swing.JLabel enter_username_label;
    private javax.swing.JPanel enter_username_panel;
    private javax.swing.JTextField enter_username_textfield;
    private javax.swing.JPanel input_message_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel message_label;
    private javax.swing.JTextField message_tf;
    private javax.swing.JScrollPane multicast_note_scrollpane;
    private javax.swing.JTextArea multicast_note_ta;
    private javax.swing.JRadioButton multicast_rb;
    private javax.swing.JButton send_btn;
    private javax.swing.JTextArea status_ta;
    private javax.swing.JScrollPane textAreaScrollPane;
    private javax.swing.JTextArea timestamp_ta;
    private javax.swing.JRadioButton unicast_rb;
    private javax.swing.JScrollPane userListScrollPane;
    private javax.swing.JTextArea username_ta;
    // End of variables declaration//GEN-END:variables

}
